// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.
// This file contains the discriminators for accounts and events defined in the IDL.

package locker

// Account discriminators
var (
	Account_RootEscrow            = [8]byte{253, 209, 220, 107, 206, 191, 71, 158}
	Account_VestingEscrow         = [8]byte{244, 119, 183, 4, 73, 116, 135, 195}
	Account_VestingEscrowMetadata = [8]byte{24, 204, 166, 104, 87, 158, 76, 13}
)

// Event discriminators
var (
	Event_EventCancelVestingEscrow          = [8]byte{113, 2, 117, 173, 195, 39, 101, 155}
	Event_EventCancelVestingEscrowV3        = [8]byte{41, 143, 236, 79, 116, 120, 91, 143}
	Event_EventClaim                        = [8]byte{171, 144, 1, 189, 120, 200, 38, 11}
	Event_EventClaimV3                      = [8]byte{229, 197, 142, 10, 41, 122, 171, 154}
	Event_EventCloseClaimStatus             = [8]byte{87, 68, 38, 194, 241, 155, 125, 107}
	Event_EventCloseVestingEscrow           = [8]byte{45, 141, 253, 209, 196, 133, 21, 204}
	Event_EventCreateRootEscrow             = [8]byte{105, 216, 97, 182, 27, 224, 199, 228}
	Event_EventCreateVestingEscrow          = [8]byte{248, 222, 89, 61, 170, 208, 131, 117}
	Event_EventFundRootEscrow               = [8]byte{74, 8, 68, 181, 198, 235, 138, 81}
	Event_EventUpdateVestingEscrowRecipient = [8]byte{206, 218, 33, 65, 133, 237, 131, 57}
)

// Instruction discriminators
var (
	Instruction_CancelVestingEscrow          = [8]byte{217, 233, 13, 3, 143, 101, 53, 201}
	Instruction_Claim                        = [8]byte{62, 198, 214, 193, 213, 159, 108, 210}
	Instruction_ClaimV2                      = [8]byte{229, 87, 46, 162, 21, 157, 231, 114}
	Instruction_CloseVestingEscrow           = [8]byte{221, 185, 95, 135, 136, 67, 252, 87}
	Instruction_CreateRootEscrow             = [8]byte{116, 212, 12, 188, 77, 226, 32, 201}
	Instruction_CreateVestingEscrow          = [8]byte{23, 100, 197, 94, 222, 153, 38, 90}
	Instruction_CreateVestingEscrowFromRoot  = [8]byte{6, 238, 161, 108, 252, 114, 246, 91}
	Instruction_CreateVestingEscrowMetadata  = [8]byte{93, 78, 33, 103, 173, 125, 70, 0}
	Instruction_CreateVestingEscrowV2        = [8]byte{181, 155, 104, 183, 182, 128, 35, 47}
	Instruction_FundRootEscrow               = [8]byte{251, 106, 189, 200, 108, 15, 144, 95}
	Instruction_UpdateVestingEscrowRecipient = [8]byte{26, 242, 127, 255, 237, 109, 47, 206}
)
