// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.
// This file contains constants.

package dynamic_bonding_curve

import (
	"math/big"

	"github.com/krazyTry/meteora-go/u128"
)

var (
	AccountKeyClaimFeeOperator             = "ClaimFeeOperator"
	AccountKeyConfig                       = "Config"
	AccountKeyLockEscrow                   = "LockEscrow"
	AccountKeyMeteoraDammMigrationMetadata = "MeteoraDammMigrationMetadata"
	AccountKeyMeteoraDammV2Metadata        = "MeteoraDammV2Metadata"
	AccountKeyPartnerMetadata              = "PartnerMetadata"
	AccountKeyPoolConfig                   = "PoolConfig"
	AccountKeyVirtualPool                  = "VirtualPool"
	AccountKeyVirtualPoolMetadata          = "VirtualPoolMetadata"
)

var (
	MIN_FEE_NUMERATOR = new(big.Int).SetUint64(100_000)     // 0.0001%
	MAX_FEE_NUMERATOR = new(big.Int).SetUint64(990_000_000) // 99%
	FEE_DENOMINATOR   = new(big.Int).SetUint64(1_000_000_000)
	BASIS_POINT_MAX   = new(big.Int).SetUint64(10000)

	MAX_FEE_BPS = int64(9900) // 99%
	MIN_FEE_BPS = int64(1)    // 0.0001%

	BIN_STEP_BPS_DEFAULT      = big.NewInt(1)
	BIN_STEP_BPS_U128_DEFAULT = u128.GenUint128FromString("1844674407370955")

	MIN_SQRT_PRICE    = new(big.Int).SetUint64(4295048016)
	MAX_SQRT_PRICE, _ = new(big.Int).SetString("79226673521066979257578248091", 10)

	DYNAMIC_FEE_FILTER_PERIOD_DEFAULT    = uint16(10)   // 10 seconds
	DYNAMIC_FEE_DECAY_PERIOD_DEFAULT     = uint16(120)  // 120 seconds
	DYNAMIC_FEE_REDUCTION_FACTOR_DEFAULT = uint16(5000) // 50%

	MAX_RATE_LIMITER_DURATION_IN_SECONDS = 43200  // 12 hours
	MAX_RATE_LIMITER_DURATION_IN_SLOTS   = 108000 // 12 hours

	MAX_PRICE_CHANGE_BPS_DEFAULT = int64(1500) // 15%

	RESOLUTION = int32(64)
	ONE_Q64    = new(big.Int).Lsh(big.NewInt(1), uint(RESOLUTION))
)

type ActivationType uint8

const (
	ActivationTypeSlot ActivationType = iota
	ActivationTypeTimestamp
)

type TokenType uint8

const (
	TokenTypeSPL TokenType = iota
	TokenTypeToken2022
)

type DammV2DynamicFeeMode uint8

const (
	DammV2DynamicFeeDisabled DammV2DynamicFeeMode = iota
	DammV2DynamicFeeEnabled
)

// MigrationOption
type MigrationOption uint8

const (
	MigrationOptionMETDAMM MigrationOption = iota
	MigrationOptionMETDAMMV2
)

// BaseFeeMode
type BaseFeeMode uint8

const (
	BaseFeeModeFeeSchedulerLinear BaseFeeMode = iota
	BaseFeeModeFeeSchedulerExponential
	BaseFeeModeRateLimiter
)

// MigrationFeeOption
type MigrationFeeOption uint8

const (
	MigrationFeeFixedBps25 MigrationFeeOption = iota
	MigrationFeeFixedBps30
	MigrationFeeFixedBps100
	MigrationFeeFixedBps200
	MigrationFeeFixedBps400
	MigrationFeeFixedBps600
	MigrationFeeCustomizable // only for DAMM v2
)

// TokenDecimal
type TokenDecimal uint8

const (
	TokenDecimalSix   TokenDecimal = 6
	TokenDecimalSeven TokenDecimal = 7
	TokenDecimalEight TokenDecimal = 8
	TokenDecimalNine  TokenDecimal = 9
)

// CollectFeeMode
type CollectFeeMode uint8

const (
	CollectFeeModeQuoteToken CollectFeeMode = iota
	CollectFeeModeOutputToken
)

// TradeDirection
type TradeDirection uint8

const (
	TradeDirectionBaseToQuote TradeDirection = iota
	TradeDirectionQuoteToBase
)

type TokenUpdateAuthorityOption uint8

const (
	TokenUpdateAuthorityCreatorUpdateAuthority TokenUpdateAuthorityOption = iota
	TokenUpdateAuthorityImmutable
	TokenUpdateAuthorityPartnerUpdateAuthority
	TokenUpdateAuthorityCreatorUpdateAndMintAuthority
	TokenUpdateAuthorityPartnerUpdateAndMintAuthority
)

type MigrationProgress uint8

const (
	MigrationProgressPreBondingCurve MigrationProgress = iota
	MigrationProgressPostBondingCurve
	MigrationProgressLockedVesting
	MigrationProgressCreatedPool
)
