// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.
// This file contains constants.

package amm

var (
	AccountKeyConfig     = "config"
	AccountKeyLockEscrow = "lockEscrow"
	AccountKeyPool       = "pool"
)
