// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.
// This file contains the discriminators for accounts and events defined in the IDL.

package amm

// Account discriminators
var (
	Account_Config     = [8]byte{113, 208, 182, 110, 90, 47, 111, 215}
	Account_LockEscrow = [8]byte{182, 49, 232, 36, 6, 251, 58, 14}
	Account_Pool       = [8]byte{209, 88, 127, 156, 213, 147, 70, 23}
)

// Event discriminators
var (
	Event_AddLiquidity         = [8]byte{31, 94, 125, 90, 227, 52, 61, 186}
	Event_RemoveLiquidity      = [8]byte{116, 244, 97, 232, 103, 31, 152, 58}
	Event_BootstrapLiquidity   = [8]byte{121, 127, 38, 136, 92, 55, 14, 247}
	Event_Swap                 = [8]byte{81, 108, 227, 190, 205, 208, 10, 196}
	Event_SetPoolFees          = [8]byte{245, 26, 198, 164, 88, 18, 75, 9}
	Event_PoolInfo             = [8]byte{207, 20, 87, 97, 251, 212, 234, 45}
	Event_TransferAdmin        = [8]byte{228, 169, 131, 244, 61, 56, 65, 254}
	Event_OverrideCurveParam   = [8]byte{247, 20, 165, 248, 75, 5, 54, 246}
	Event_PoolCreated          = [8]byte{202, 44, 41, 88, 104, 220, 157, 82}
	Event_PoolEnabled          = [8]byte{2, 151, 18, 83, 204, 134, 92, 191}
	Event_MigrateFeeAccount    = [8]byte{223, 234, 232, 26, 252, 105, 180, 125}
	Event_CreateLockEscrow     = [8]byte{74, 94, 106, 141, 49, 17, 98, 109}
	Event_Lock                 = [8]byte{220, 183, 67, 215, 153, 207, 56, 234}
	Event_ClaimFee             = [8]byte{75, 122, 154, 48, 140, 74, 123, 163}
	Event_CreateConfig         = [8]byte{199, 152, 10, 19, 39, 39, 157, 104}
	Event_CloseConfig          = [8]byte{249, 181, 108, 89, 4, 150, 90, 174}
	Event_WithdrawProtocolFees = [8]byte{30, 240, 207, 196, 139, 239, 79, 28}
	Event_PartnerClaimFees     = [8]byte{135, 131, 10, 94, 119, 209, 202, 48}
	Event_MoveLockedLp         = [8]byte{216, 16, 4, 23, 77, 90, 170, 139}
)

// Instruction discriminators
var (
	Instruction_InitializePermissionedPool                              = [8]byte{77, 85, 178, 157, 50, 48, 212, 126}
	Instruction_InitializePermissionlessPool                            = [8]byte{118, 173, 41, 157, 173, 72, 97, 103}
	Instruction_InitializePermissionlessPoolWithFeeTier                 = [8]byte{6, 135, 68, 147, 229, 82, 169, 113}
	Instruction_EnableOrDisablePool                                     = [8]byte{128, 6, 228, 131, 55, 161, 52, 169}
	Instruction_Swap                                                    = [8]byte{248, 198, 158, 145, 225, 117, 135, 200}
	Instruction_RemoveLiquiditySingleSide                               = [8]byte{84, 84, 177, 66, 254, 185, 10, 251}
	Instruction_AddImbalanceLiquidity                                   = [8]byte{79, 35, 122, 84, 173, 15, 93, 191}
	Instruction_RemoveBalanceLiquidity                                  = [8]byte{133, 109, 44, 179, 56, 238, 114, 33}
	Instruction_AddBalanceLiquidity                                     = [8]byte{168, 227, 50, 62, 189, 171, 84, 176}
	Instruction_SetPoolFees                                             = [8]byte{102, 44, 158, 54, 205, 37, 126, 78}
	Instruction_OverrideCurveParam                                      = [8]byte{98, 86, 204, 51, 94, 71, 69, 187}
	Instruction_GetPoolInfo                                             = [8]byte{9, 48, 220, 101, 22, 240, 78, 200}
	Instruction_BootstrapLiquidity                                      = [8]byte{4, 228, 215, 71, 225, 253, 119, 206}
	Instruction_CreateMintMetadata                                      = [8]byte{13, 70, 168, 41, 250, 100, 148, 90}
	Instruction_CreateLockEscrow                                        = [8]byte{54, 87, 165, 19, 69, 227, 218, 224}
	Instruction_Lock                                                    = [8]byte{21, 19, 208, 43, 237, 62, 255, 87}
	Instruction_ClaimFee                                                = [8]byte{169, 32, 79, 137, 136, 232, 70, 137}
	Instruction_CreateConfig                                            = [8]byte{201, 207, 243, 114, 75, 111, 47, 189}
	Instruction_CloseConfig                                             = [8]byte{145, 9, 72, 157, 95, 125, 61, 85}
	Instruction_InitializePermissionlessConstantProductPoolWithConfig   = [8]byte{7, 166, 138, 171, 206, 171, 236, 244}
	Instruction_InitializePermissionlessConstantProductPoolWithConfig2  = [8]byte{48, 149, 220, 130, 61, 11, 9, 178}
	Instruction_InitializeCustomizablePermissionlessConstantProductPool = [8]byte{145, 24, 172, 194, 219, 125, 3, 190}
	Instruction_UpdateActivationPoint                                   = [8]byte{150, 62, 125, 219, 171, 220, 26, 237}
	Instruction_WithdrawProtocolFees                                    = [8]byte{11, 68, 165, 98, 18, 208, 134, 73}
	Instruction_SetWhitelistedVault                                     = [8]byte{12, 148, 94, 42, 55, 57, 83, 247}
	Instruction_PartnerClaimFee                                         = [8]byte{57, 53, 176, 30, 123, 70, 52, 64}
	Instruction_MoveLockedLp                                            = [8]byte{40, 210, 34, 53, 233, 95, 232, 143}
)
